### PR TITLE
`Modeling Exercise`: Visual enhancements

### PR DESCRIPTION
**Pull request by terlan98**
> ⚠️ Should be merged after #170 

This PR includes some visual improvements for modeling exercises:
- Abstract class names are now italic
- Elements with feedback suggestions now only have highlighted titles instead of a highlight covering them completely
- Relationship highlights now perfectly match the relationship path

| Before | After |
|--------|--------|
| Screenshot 2023-08-28 at 14 06 33 | Screenshot 2023-08-28 at 14 03 49 |

### CODE REVIEW

**Review by AlexanderG2207 — COMMENTED** [review]
I tested locally, and everything works well! The code itself also looks good, nice!

I don't know why the build has an error, as I don't have the correct permissions. Is it because of it being a stacked PR?

**Comment by terlan98** [comment]
@AlexanderG2207, thanks for the review! 🙏 
The builds are failing because the account holder needs to accept the new Apple developer license agreement and he/she is currently on vacation 🙂

**Review by maximiliansoelch — APPROVED** [review]
Code looks good, tested locally, works as expected 👍

**Review by AlexanderG2207 — APPROVED** [review]
@terlan98 Understood 👍

**Pull request merged**
