### PR TITLE
Implement token-cookie switching based on server version

### PR DESCRIPTION
**Pull request by pal03377**
I cannot really test it completely because I don't have a tutor account on a current 5.x Artemis server. It would be good if someone with access could test it (@katjanakosic ?).

### CODE REVIEW

**Comment by botrufus** [comment]
Why do you need a Tutor account? As long as the login works and courses and exercises can be fetched, everything should work.

**Comment by pal03377** [comment]
> Why do you need a Tutor account? As long as the login works and courses and exercises can be fetched, everything should work.

Ok, that does not work and I was not sure if it was because of my permissions or not. I guess I need to work on it 😅

**Comment by pal03377** [comment]
Sorry that I took so long that the Artemis 6.0 release on artemis.ase.in.tum.de is right around the corner (Jan 23, 7:00 am). You might not be able to test bearer-token auth yourself anymore 😬 

I just tested it and it works though

**Comment by pal03377** [comment]
Sorry that I took so long that the Artemis 6.0 release on artemis.ase.in.tum.de is right around the corner (Jan 23, 7:00 am). You might not be able to test bearer-token auth yourself anymore 😬 

I just tested it and it works though

**Review by huber-florian — APPROVED** [review]
I've tested it and it works very well! Good job Paul!

**Review by botrufus — APPROVED** [review]
Code looks good, cookie auth also works

**Pull request merged**
