### PR TITLE
Course overview on top right

### PR DESCRIPTION
**Pull request by pal03377**
screenshot-2023-01-06_000847

### CODE REVIEW

**Comment by pal03377** [comment]
Request @reviewers: If you have an idea for a nicer name for the `CourseListView` (after all, now it's just the `ExerciseView` with a picker), feel free to suggest one.

**Comment by botrufus** [comment]
What about the design from the mock you did?
Ok nvm I thought its the exercise view you worked on.
Just CourseListView -> CourseView
And I would remove the 'Exercises' part of the title as its clear anyway and rather confusing.

**Comment by pal03377** [comment]
> What about the design from the mock you did? Ok nvm I thought its the exercise view you worked on. Just CourseListView -> CourseView And I would remove the 'Exercises' part of the title as its clear anyway and rather confusing.

Good suggestions! I've added a commit for them

**Review by crustypluto19 — APPROVED** [review]
Looks great! 💯

**Comment by botrufus** [comment]
The CourseListViewModel File and corresponding folder still need to be renamed.

**Comment by pal03377** [comment]
Oops, @tomrudnick and me changed it at the same time 😅 Now it should work again

**Review by botrufus — APPROVED** [review]

**Pull request merged**
