### PR TITLE
Score display and some bug fixes

### PR DESCRIPTION
**Pull request by botrufus**
- Add score display (animated progressview or "Build failed"): 
image
- bugfix: feedback is now correctly displayed as manual or automatic feedback in Artemis and re-assessment view
image
- bugfix: navigation bar / navigation bar background is now properly working in re-assessment (fix in submissionviewloader)
- small design change: increased size of save and submit button

### CODE REVIEW

**Review by katjanakosic — APPROVED** [review]
Looks good to me 👍🏻 just a minor comment: it looks a bit weird (to me) that the settings button is prior to the overall score. Maybe adding it behind the score looks nicer idk. What do you think? :)

**Comment by botrufus** [comment]
> Looks good to me 👍🏻 just a minor comment: it looks a bit weird (to me) that the settings button is prior to the overall score. Maybe adding it behind the score looks nicer idk. What do you think? :)

Yes, thought so as well. However I think that the settings button should be removed and "hidden" somewhere else as Jan Philip already mentioned in the last customer meeting.

**Review by pal03377 — CHANGES_REQUESTED** [review]
Very nice & looks very good! I have just one small request: Could you put the `progressView` into a separate file? It would just have to be a view that takes a `score: Int` and a `maximumScore: Int` and displays the little ring and the text next to it. Otherwise the AssessmentView becomes a bit cluttered imo.

I think the settings icon is fine, it will be removed eventually anyways.

**Comment by botrufus** [comment]
- Added an extra view for the progress view
- Updated the formatting to make the score look a bit better
image

**Review by pal03377 — APPROVED** [review]
Fantastic!

**Comment by huber-florian** [comment]
Cool!

**Review by huber-florian — APPROVED** [review]

**Pull request merged**
