### PR TITLE
Add programming exercise symbol

### PR DESCRIPTION
**Pull request by tcw0**
- Used SFSymbol, since Artemis svg files for the symbols
- Can only add it to the programming exercises, since we are only fetching programming exercises from Artemis and therefore don't have a parameter for different exercise types

### CODE REVIEW

**Comment by huber-florian** [comment]
Can you add a screenshot?

**Comment by AlexExcellence** [comment]
We are actually fetching all types of exercises from Artemis, but your'e right about the exercise type not being stored. Is it even sent with the Api Call we are using?

**Comment by huber-florian** [comment]
image

**Comment by huber-florian** [comment]
It's a simple approach but it works for now. At least for it's fine to keep it simple here.

**Review by huber-florian — APPROVED** [review]
It's a simple approach but it works for now. At least for it's fine to keep it simple here.

**Comment by AlexExcellence** [comment]
I would say we have these options:
- Leave the symbols out completely (keeping them like they are right now is confusing since then e.g. quiz exercises are marked as programming exercises)
- Also fetch the category of the exersise and store it in the struct to be able to distinguish the exercise types properly
- Only fetch programming exercises and show the currently used symbol (afaik the required api call is already implemented, but not used atm)

**Comment by botrufus** [comment]
> Only fetch programming exercises and show the currently used symbol (afaik the required api call is already implemented, but not used atm)

~~Could silently break some things, as the response could look different i.e. some fields could be missing compared to the current one.~~

~~I also don't see a reason to put those icons in when the icons for other exercises are not properly set.~~

**Comment by botrufus** [comment]
> We are actually fetching all types of exercises from Artemis, but your'e right about the exercise type not being stored. Is it even sent with the Api Call we are using?

This is not true anymore. Only programming exercises are fetched.

**Comment by botrufus** [comment]
I quickly added two more things that were missing for the exams but fit into this PR:
- exercise icons for exercises in exam
- bug fix: disable the possibility to navigate to exercise types other than programming

image

image

**Review by botrufus — APPROVED** [review]

**Comment by AlexExcellence** [comment]
Great additions rufus, thank you!

**Pull request merged**
