### PR TITLE
Changed Icon and selection behaviour (see video)

### PR DESCRIPTION
**Pull request by tomrudnick**
https://user-images.githubusercontent.com/16856573/213204139-9e538f2d-84c7-4a8f-879b-5538f0501629.MP4

### CODE REVIEW

**Review by botrufus — APPROVED** [review]
Nice. But why the yellow color for the hand image?

**Comment by tomrudnick** [comment]
> Nice. But why the yellow color for the hand image?

I just copied the coloring from before and the "Aa" is also yellow when it's active so I thought I stick to the "color scheme".
But I don't care

**Comment by botrufus** [comment]
> I just copied the coloring from before and the "Aa" is also yellow when it's active so I thought I stick to the "color scheme".
> But I don't care

Ok, I would just do it white. Same for the code size button. Or what do the others think?

**Comment by huber-florian** [comment]
I like the yellow but I would not have a problem with white as well.

**Review by huber-florian — APPROVED** [review]
Good job!

**Comment by tomrudnick** [comment]
@botrufus hm ok I tried white and in my opinion yellow looks better so I think I leave as it is for the moment and we can change it in the future if other people or the customer wants it white

**Pull request merged**
