### PR TITLE
Cancel Dialog for cancel button

### PR DESCRIPTION
**Pull request by botrufus**
As discussed in last Wednesdays meeting: the option to discard and release the lock or save the assessment.
Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2022-12-04 at 11 54 55

### CODE REVIEW

**Review by pal03377 — CHANGES_REQUESTED** [review]
Very nice! However, there now is a new bug after cancelling: The submission list still includes the submission after cancelling it. Previously, it wasn't there after going back.

screenshot-2022-12-04_000763

**Comment by botrufus** [comment]
> Very nice! However, there now is a new bug after cancelling: The submission list still includes the submission after cancelling it. Previously, it wasn't there after going back.

yes I noticed that, but was pretty sure that its not because if my changes. Will take a look at it.

**Comment by botrufus** [comment]
@pal03377 fixed

**Review by pal03377 — APPROVED** [review]
Well done!

**Review by AlexExcellence — APPROVED** [review]

**Pull request merged**
