### PR TITLE
Compile time improvement

### PR DESCRIPTION
**Pull request by tomrudnick**
The Compile time is very slow.
I improved it.
Compiling the cleaned project before:
37.4 seconds
Now:
15.8 seconds

Pipeline before:
4 minutes
Now:
2 minutes

I also removed an old timer for my parser ^^

### CODE REVIEW

**Review by botrufus — APPROVED** [review]
I sadly can't test if it's faster or not as it anyways takes minutes for me instead of seconds :(. What is/was the exact reason for the slow compilation time?

**Review by crustypluto19 — APPROVED** [review]
Compiles faster!

**Comment by tomrudnick** [comment]
> I sadly can't test if it's faster or not as it anyways takes minutes for me instead of seconds :(. What is/was the exact reason for the slow compilation time?

I think the View that I changed was too complicated. It had many View Modifiers If else and so on and  I guess it took longer to type check. Splitting it up helped the compiler to deduce the correct type faster

**Comment by tomrudnick** [comment]
> > I sadly can't test if it's faster or not as it anyways takes minutes for me instead of seconds :(. What is/was the exact reason for the slow compilation time?
> 
> I think the View that I changed was too complicated. It had many View Modifiers If else and so on and I guess it took longer to type check. Splitting it up helped the compiler to deduce the correct type faster

And furthermore If you now change something in a View that is closely related to this file, it does not need to recompile this complicated View anymore (I guess)

**Pull request merged**
