### PR TITLE
Filebrowser icons

### PR DESCRIPTION
**Pull request by tomrudnick**
I added Icons for the Filebrowser.
I used a submodule for those icons (Devicon) and made a small Wrapper Package to extract the images from
the submodule. In the Future, I might add a caching system so that the images are loaded faster.

IMG_8C8272728B90-1

### CODE REVIEW

**Comment by pal03377** [comment]
Purely from the screenshot, I think it's a little bit weird that the Gradle icons are black/white and the Java icons are colored. Is there a way to make this consistent?

**Comment by huber-florian** [comment]
> Purely from the screenshot, I think it's a little bit weird that the Gradle icons are black/white and the Java icons are colored. Is there a way to make this consistent?

Well, the gradle logo is always black, so it couldn't be another color. But to answer your question, in this package is no black/white java logo so we have to deal with that.

**Comment by pal03377** [comment]
> in this package is no black/white java logo so we have to deal with that

Well, there's `.saturation(0.0)`, we could think about whether that improves or worsens the appearance.

**Comment by huber-florian** [comment]
image

For me, it does not build...

**Comment by pal03377** [comment]
Same here.

screenshot-2023-01-23_000937

**Comment by tomrudnick** [comment]
Well for some reason this whole package thing was completely awful, I implemented it now differently so I close this pr and open another one when I'm finished

**Pull request closed without merging**
