### PR TITLE
optimize correction guidelines readability

### PR DESCRIPTION
**Pull request by huber-florian**
This PR improves the readability of correction guidelines.
Bildschirm­foto 2022-12-05 um 00 03 38

### CODE REVIEW

**Review by katjanakosic — APPROVED** [review]
Looks very nice! 👍🏻

**Review by crustypluto19 — APPROVED** [review]
Looks great! 👍 Should we also implement this design (colored rounded corners based on feedback) in the feedback tab? That way it'll look more uniform :)

**Comment by huber-florian** [comment]
> Looks great! 👍 Should we also implement this design (colored rounded corners based on feedback) in the feedback tab? That way it'll look more uniform :)

Thank you. Definitely good idea.

**Comment by huber-florian** [comment]
> Looks great! 👍 Should we also implement this design (colored rounded corners based on feedback) in the feedback tab? That way it'll look more uniform :)

Thank you.

**Pull request merged**
