### PR TITLE
Implemented pan and zoom

### PR DESCRIPTION
**Pull request by crustypluto19**
I have removed the drag up/down to dismiss the UML Viewer as I think it interferes greatly with panning and zooming, but I still keep the function for opacity effects in the UMLViewModel just in case we want to revert back to it.

It looks like this now:

https://user-images.githubusercontent.com/24537483/207204242-b652a177-631f-4d3d-b392-86f30509f6fe.mp4

As always if you have an iPad please test it locally :)
@tomrudnick hopefully this time CPU consumption won't get any worse ;)

### CODE REVIEW

**Review by pal03377 — APPROVED** [review]
I like it! Dragging still feels a bit weird because it lags behind and also sometimes jumps a bit, also when you zoom, you are first reset to the initial zoom level and only then can actually zoom. Still, it's definitely a good improvement!

**Comment by pal03377** [comment]
Screen recording of how it looks on my iPad:

https://user-images.githubusercontent.com/9006596/207317819-05f6e62a-3f5f-4831-8eeb-59b7a4a5ba04.MP4

**Comment by crustypluto19** [comment]
Refactored UML Viewer
- performance issue should now be fixed (with CachedAsyncImage)
- dragging should now be working properly (not "jumpy")
- reset image scale after exiting the viewer

https://user-images.githubusercontent.com/24537483/211945165-b25c42d0-2f4b-4e6a-b60b-5e4663034472.mp4

**Comment by AlexExcellence** [comment]
Build is failing for me, please check

**Review by huber-florian — APPROVED** [review]
Looks good!

**Pull request merged**
