### PR TITLE
Minor documentation improvements

### PR DESCRIPTION
**Pull request by pal03377**
- restructured administrator manual to be split into two sections (Themis App & ThemisML)
- more consistency about the name "ThemisML" (no space, usually no "server" except where explicitly meant)
- fix Sphinx build warnings (broken links, wrong indentations, too few headline underline-characters)
- more consistent capitalization of headings

### CODE REVIEW

**Comment by pal03377** [comment]
I hope I got the part about splitting the Administrator Manual right, I only took a quick note in the meeting today

**Comment by huber-florian** [comment]
image

That double headline looks a bit weird. Same for Themis ML.

**Comment by huber-florian** [comment]
I have removed the unnecessary pipes.

**Comment by pal03377** [comment]
> image
> 
> That double headline looks a bit weird. Same for Themis ML.

Thanks for the note! It's fixed now 👍

**Review by huber-florian — APPROVED** [review]
Thank you Paul for your initiative here and throughout the whole project!

**Review by katjanakosic — APPROVED** [review]
Looks good to me 🙌

**Pull request merged**
